// Read, merge, backup, and write .env files for onboarding setup
import { readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';
import type { SetupResult } from './setup-wizard.js';

/** Parse a .env file into a key-value map (ignores comments and blank lines) */
export function readEnvFile(path: string): Map<string, string> {
  const map = new Map<string, string>();
  if (!existsSync(path)) return map;
  const lines = readFileSync(path, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    map.set(key, value);
  }
  return map;
}

/** Copy current .env to .env.backup before overwriting */
export function backupEnvFile(path: string): void {
  if (existsSync(path)) {
    copyFileSync(path, `${path}.backup`);
  }
}

/** Merge updates into existing env map; updates win on conflict */
export function mergeEnvFile(
  existing: Map<string, string>,
  updates: Map<string, string>,
): Map<string, string> {
  const merged = new Map(existing);
  for (const [k, v] of updates) {
    merged.set(k, v);
  }
  return merged;
}

/** Serialize a key-value map into .env file format */
function serializeEnvMap(map: Map<string, string>): string {
  const lines: string[] = ['# Generated by algo-trade setup wizard', ''];
  for (const [key, value] of map) {
    // Quote values that contain spaces
    const needsQuote = value.includes(' ') || value.includes('#');
    lines.push(`${key}=${needsQuote ? `"${value}"` : value}`);
  }
  return lines.join('\n') + '\n';
}

/** Build env map from SetupResult */
function buildEnvMap(config: SetupResult): Map<string, string> {
  const map = new Map<string, string>();

  map.set('NODE_ENV', config.environment);
  map.set('LOG_LEVEL', config.environment === 'production' ? 'info' : 'debug');
  map.set('DB_PATH', './data/algo-trade.db');

  // Risk limits
  map.set('MAX_POSITION_SIZE', config.riskLimits.maxPositionSize);
  map.set('MAX_DRAWDOWN', String(config.riskLimits.maxDrawdown));
  map.set('MAX_OPEN_POSITIONS', String(config.riskLimits.maxOpenPositions));
  map.set('STOP_LOSS_PERCENT', String(config.riskLimits.stopLossPercent));
  map.set('MAX_LEVERAGE', String(config.riskLimits.maxLeverage));

  // Exchange credentials
  if (config.exchanges.binance) {
    map.set('BINANCE_API_KEY', config.exchanges.binance.apiKey);
    map.set('BINANCE_API_SECRET', config.exchanges.binance.apiSecret);
  }
  if (config.exchanges.bybit) {
    map.set('BYBIT_API_KEY', config.exchanges.bybit.apiKey);
    map.set('BYBIT_API_SECRET', config.exchanges.bybit.apiSecret);
  }
  if (config.exchanges.okx) {
    map.set('OKX_API_KEY', config.exchanges.okx.apiKey);
    map.set('OKX_API_SECRET', config.exchanges.okx.apiSecret);
    if (config.exchanges.okx.passphrase) {
      map.set('OKX_PASSPHRASE', config.exchanges.okx.passphrase);
    }
  }
  if (config.exchanges.polymarket) {
    map.set('POLYMARKET_PRIVATE_KEY', config.exchanges.polymarket.privateKey ?? '');
    map.set('POLYMARKET_CLOB_URL', 'https://clob.polymarket.com');
    map.set('POLYMARKET_CHAIN_ID', '137');
    map.set('POLYGON_RPC_URL', 'https://polygon-rpc.com');
  }

  // Notification channel
  if (config.notificationChannel === 'telegram' && config.notificationToken) {
    map.set('TELEGRAM_BOT_TOKEN', config.notificationToken);
  } else if (config.notificationChannel === 'discord' && config.notificationToken) {
    map.set('DISCORD_WEBHOOK_URL', config.notificationToken);
  } else if (config.notificationChannel === 'slack' && config.notificationToken) {
    map.set('SLACK_WEBHOOK_URL', config.notificationToken);
  }

  // Platform API key (generated during setup)
  if (config.platformApiKey) map.set('PLATFORM_API_KEY', config.platformApiKey);
  if (config.webhookSecret) map.set('WEBHOOK_SECRET', config.webhookSecret);

  return map;
}

/** Write SetupResult to .env file at given path (backs up existing file first) */
export function writeEnvFile(config: SetupResult, path: string): void {
  backupEnvFile(path);
  const map = buildEnvMap(config);
  writeFileSync(path, serializeEnvMap(map), 'utf8');
}
