/**
 * Base Agent — Abstract foundation for all trading agents.
 * Implements Plan-Execute-Verify pattern with A2UI event publishing.
 */

import { AgentEventBus } from '../a2ui/agent-event-bus';
import { AutonomyLevel, AgentEventType } from '../a2ui/types';
import { logger } from '../utils/logger';

/** Trading event input for agent processing */
export interface TradingEvent {
  type: 'MARKET_DATA' | 'SIGNAL' | 'POSITION_UPDATE' | 'RISK_ALERT';
  symbol: string;
  timestamp: number;
  data: Record<string, unknown>;
  tenantId: string;
}

/** Action plan generated by planning phase */
export interface ActionPlan {
  agentId: string;
  actions: Array<{
    type: 'ANALYZE' | 'DECIDE' | 'EXECUTE' | 'MONITOR';
    description: string;
    params: Record<string, unknown>;
  }>;
  confidence: number;
  rationale: string;
}

/** Execution result from running a plan */
export interface ExecutionResult {
  success: boolean;
  output: Record<string, unknown>;
  error?: string;
  duration: number;
}

/** Verification result from validating execution */
export interface VerificationResult {
  passed: boolean;
  score: number; // 0-1
  findings: string[];
  recommendations: string[];
}

/**
 * Abstract base class for all trading agents.
 * Enforces Plan-Execute-Verify pattern with event publishing.
 */
export abstract class BaseAgent {
  protected eventBus: AgentEventBus;
  protected autonomyLevel: AutonomyLevel;
  protected readonly agentId: string;

  constructor(agentId: string, eventBus: AgentEventBus, autonomyLevel: AutonomyLevel = AutonomyLevel.ACT_CONFIRM) {
    this.agentId = agentId;
    this.eventBus = eventBus;
    this.autonomyLevel = autonomyLevel;
  }

  /**
   * Plan phase: Analyze event and generate action plan.
   * Must be implemented by each agent type.
   */
  abstract plan(event: TradingEvent): Promise<ActionPlan>;

  /**
   * Execute phase: Run the action plan.
   * Must be implemented by each agent type.
   */
  abstract execute(plan: ActionPlan, event?: TradingEvent): Promise<ExecutionResult>;

  /**
   * Verify phase: Validate execution results.
   * Must be implemented by each agent type.
   */
  abstract verify(result: ExecutionResult): Promise<VerificationResult>;

  /**
   * Process an event through Plan-Execute-Verify pipeline.
   * Template method - defines the skeleton, subclasses fill in details.
   */
  async process(event: TradingEvent): Promise<VerificationResult> {
    const startTime = Date.now();

    try {
      // Plan
      logger.debug(`[${this.agentId}] Planning for ${event.symbol}`);
      const plan = await this.plan(event);

      // Execute
      logger.debug(`[${this.agentId}] Executing plan with ${plan.actions.length} actions`);
      const result = await this.execute(plan);

      // Verify
      logger.debug(`[${this.agentId}] Verifying execution result`);
      const verification = await this.verify(result);

      // Publish result
      await this.publish(verification, event, plan, result, Date.now() - startTime);

      return verification;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      logger.error(`[${this.agentId}] Process failed: ${errorMessage}`);

      const failedVerification: VerificationResult = {
        passed: false,
        score: 0,
        findings: [`Process failed: ${errorMessage}`],
        recommendations: ['Review agent configuration', 'Check input data validity'],
      };

      await this.publish(failedVerification, event);
      return failedVerification;
    }
  }

  /**
   * Publish verification result to event bus.
   * Override in subclasses to add agent-specific event types.
   */
  protected async publish(
    verification: VerificationResult,
    event?: TradingEvent,
    plan?: ActionPlan,
    result?: ExecutionResult,
    duration?: number
  ): Promise<void> {
    await this.eventBus.emit({
      type: AgentEventType.THOUGHT_SUMMARY,
      tenantId: event?.tenantId ?? 'default',
      timestamp: Date.now(),
      steps: plan?.actions.map(a => a.description) ?? [],
      conclusion: verification.passed ? 'Success' : 'Failed',
    });
  }

  /** Get current autonomy level */
  getAutonomyLevel(): AutonomyLevel {
    return this.autonomyLevel;
  }

  /** Set autonomy level */
  setAutonomyLevel(level: AutonomyLevel): void {
    this.autonomyLevel = level;
  }

  /** Get agent ID */
  getId(): string {
    return this.agentId;
  }
}
